In [1]:
import numpy as np
# 列ベクトル：2行1列のnumpy.ndarrayを定義
w = np.array([ [5.0],[3.0] ])
# 行ベクトル：1行2列のnumpy.ndarrayを定義
x = np.array([ [1.0,5.0] ])
# 全ての要素が0または1の1行5列のnumpy.ndarrayを生成
zeros = np.zeros([1,5])
ones = np.ones([1,5])
# 一様分布または正規分布に従ってランダムに1行5列のnumpy.ndarrayを生成
uniform = np.random.rand(1,5)
normal = np.random.normal(size=[1,5])

In [3]:
# 標準出力
print(f"ベクトルw）形:{w.shape},型:{w.dtype}\n{w}\n")
print(f"ベクトルx）形:{x.shape},型:{x.dtype}\n{x}\n")
print(f"ベクトルzeros）形:{zeros.shape},型:{zeros.dtype}\n{zeros}\n")
print(f"ベクトルones）形:{ones.shape},型:{ones.dtype}\n{ones}\n")
print(f"ベクトルuniform）形:{uniform.shape},型:{uniform.dtype}\n{uniform}\n")
print(f"ベクトルnormal）形:{normal.shape},型:{normal.dtype}\n{normal}")

ベクトルw）形:(2, 1),型:float64
[[5.]
 [3.]]

ベクトルx）形:(1, 2),型:float64
[[1. 5.]]

ベクトルzeros）形:(1, 5),型:float64
[[0. 0. 0. 0. 0.]]

ベクトルones）形:(1, 5),型:float64
[[1. 1. 1. 1. 1.]]

ベクトルuniform）形:(1, 5),型:float64
[[0.97744978 0.22182144 0.97150524 0.54102012 0.30127277]]

ベクトルnormal）形:(1, 5),型:float64
[[-0.01215424 -0.19158299 -1.06417676  1.13726584 -0.41076789]]


In [4]:
# 行列：3行2列のnumpy.ndarrayを定義
X = np.array([ [1.0,2.0],[2.0,4.0],[3.0,6.0] ])
# 1行目の行ベクトル(1行2列)の取り出し
Xrow1 = X[[0], :]
# 2列目の列ベクトル(3行1列)の取り出し
Xcol2 = X[:, [1]]
# 標準出力
print(f"行列X）形:{X.shape},型:{X.dtype}\n{X}\n")
print(f"1行目）形:{Xrow1.shape},型:{Xrow1.dtype}\n{Xrow1}\n")
print(f"2列目）形:{Xcol2.shape},型:{Xcol2.dtype}\n{Xcol2}\n")

行列X）形:(3, 2),型:float64
[[1. 2.]
 [2. 4.]
 [3. 6.]]

1行目）形:(1, 2),型:float64
[[1. 2.]]

2列目）形:(3, 1),型:float64
[[2.]
 [4.]
 [6.]]



In [5]:
# 1行目の行ベクトル(1行2列)の取り出し（リストなしで指定）
Xrow1 = X[0, :]
# 標準出力
print(f"1行目）形:{Xrow1.shape},型:{Xrow1.dtype}\n{Xrow1}\n")
# 1行目の行ベクトル(1行2列)の取り出し（リストで指定）
Xrow1 = X[[0], :]
# 標準出力
print(f"1行目）形:{Xrow1.shape},型:{Xrow1.dtype}\n{Xrow1}\n")

1行目）形:(2,),型:float64
[1. 2.]

1行目）形:(1, 2),型:float64
[[1. 2.]]



In [6]:
# 列ベクトルb：3行1列のnumpy.ndarrayを定義
b = np.array([ [1.0],[1.0],[1.0] ])
# 行列とベクトルの積と和
result = np.matmul(X, w) + b
# 標準出力
print(f"積和の結果）\n{result}")

積和の結果）
[[12.]
 [23.]
 [34.]]


In [8]:
# 行列：2行2列のnumpy.ndarrayを定義
A = np.array([ [6.0,2.0],[2.0,5.0] ])
B = np.array([ [6.0,3.0],[2.0,1.0] ])
# 行列のランクの計算
rankA = np.linalg.matrix_rank(A)
rankB = np.linalg.matrix_rank(B)
# Aの逆行列
if rankA == len(A):
    invA = np.linalg.inv(A)
    print(f"行列A）ランク:{rankA}\n逆行列:\n{invA}\n")
else:
    print(f"行列A）ランク:{rankA},特異行列\n")
# Bの逆行列
if rankB == len(B):
    invB = np.linalg.inv(B)
    print(f"行列B）ランク:{rankB}\n逆行列:\n{invB}\n")
else:
    print(f"行列B）ランク:{rankB},特異行列\n")

行列A）ランク:2
逆行列:
[[ 0.19230769 -0.07692308]
 [-0.07692308  0.23076923]]

行列B）ランク:1,特異行列



In [9]:
# Bの逆行列（エラーが出る）
invB = np.linalg.inv(B)
print(f"行列B）ランク:{rankB}\n逆行列:\n{invB}\n")

LinAlgError: Singular matrix

In [10]:
# 行列式の計算
detA = np.linalg.det(A)
detB = np.linalg.det(B)
# 標準出力
print(f"行列Aの行列式:{detA:.1f}")
print(f"行列Bの行列式:{detB:.1f}")

行列Aの行列式:26.0
行列Bの行列式:0.0


In [11]:
# 行列Aの定義
A = np.array([ [3,2],[4,1] ])
# 固有値問題の解
L,V = np.linalg.eig(A)
# 標準出力
print(f"固有値:\n{L}")
print(f"固有ベクトル:\n{V}")

固有値:
[ 5. -1.]
固有ベクトル:
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]
